repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
-   repo: local
    hooks:
    -   id: ty
        name: ty
        entry: uv run ty check
        language: system
        pass_filenames: false
        always_run: true

ci:
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
    autoupdate_schedule: monthly
