from dataclasses import dataclass, asdict


@dataclass
class Card:
    name: str
    cost: int


@dataclass(frozen=True)
class _CardsNamespace:
    ARCHER_QUEEN: Card = Card("archer_queen", 5)
    ARCHERS: Card = Card("archers", 3)
    ARROWS: Card = Card("arrows", 3)
    BALLOON: Card = Card("balloon", 5)
    BANDIT: Card = Card("bandit", 3)
    BARBARIAN_BARREL: Card = Card("barbarian_barrel", 2)
    BARBARIAN_HUT: Card = Card("barbarian_hut", 7)
    BARBARIANS: Card = Card("barbarians", 5)
    BATS: Card = Card("bats", 2)
    BATTLE_HEALER: Card = Card("battle_healer", 4)
    BATTLE_RAM: Card = Card("battle_ram", 4)
    BLANK: Card = Card("blank", 11)
    BOMBER: Card = Card("bomber", 2)
    BOMB_TOWER: Card = Card("bomb_tower", 4)
    BOWLER: Card = Card("bowler", 5)
    CANNON: Card = Card("cannon", 3)
    CANNON_CART: Card = Card("cannon_cart", 5)
    CLONE: Card = Card("clone", 3)
    DART_GOBLIN: Card = Card("dart_goblin", 3)
    DARK_PRINCE: Card = Card("dark_prince", 4)
    EARTHQUAKE: Card = Card("earthquake", 3)
    ELECTRO_DRAGON: Card = Card("electro_dragon", 5)
    ELECTRO_GIANT: Card = Card("electro_giant", 7)
    ELECTRO_SPIRIT: Card = Card("electro_spirit", 1)
    ELECTRO_WIZARD: Card = Card("electro_wizard", 4)
    ELITE_BARBARIANS: Card = Card("elite_barbarians", 6)
    ELIXIR_COLLECTOR: Card = Card("elixir_collector", 6)
    ELIXIR_GOLEM: Card = Card("elixir_golem", 3)
    EXECUTIONER: Card = Card("executioner", 5)
    FIRE_SPIRIT: Card = Card("fire_spirit", 1)
    FIREBALL: Card = Card("fireball", 4)
    FIRECRACKER: Card = Card("firecracker", 3)
    FISHERMAN: Card = Card("fisherman", 3)
    FLYING_MACHINE: Card = Card("flying_machine", 4)
    FREEZE: Card = Card("freeze", 4)
    FURNACE: Card = Card("furnace", 4)
    GIANT: Card = Card("giant", 5)
    GIANT_SKELETON: Card = Card("giant_skeleton", 6)
    GIANT_SNOWBALL: Card = Card("giant_snowball", 2)
    GOBLINS: Card = Card("goblins", 2)
    GOBLIN_BARREL: Card = Card("goblin_barrel", 3)
    GOBLIN_CAGE: Card = Card("goblin_cage", 4)
    GOBLIN_DRILL: Card = Card("goblin_drill", 4)
    GOBLIN_GANG: Card = Card("goblin_gang", 3)
    GOBLIN_GIANT: Card = Card("goblin_giant", 6)
    GOBLIN_HUT: Card = Card("goblin_hut", 5)
    GOLDEN_KNIGHT: Card = Card("golden_knight", 4)
    GOLEM: Card = Card("golem", 8)
    GRAVEYARD: Card = Card("graveyard", 5)
    GUARDS: Card = Card("guards", 3)
    HEAL_SPIRIT: Card = Card("heal_spirit", 1)
    HOG_RIDER: Card = Card("hog_rider", 4)
    HUNGRY_DRAGON: Card = Card("hungry_dragon", 4)
    HUNTER: Card = Card("hunter", 4)
    ICE_GOLEM: Card = Card("ice_golem", 2)
    ICE_SPIRIT: Card = Card("ice_spirit", 1)
    ICE_WIZARD: Card = Card("ice_wizard", 3)
    INFERNO_DRAGON: Card = Card("inferno_dragon", 4)
    INFERNO_TOWER: Card = Card("inferno_tower", 5)
    KNIGHT: Card = Card("knight", 3)
    LAVA_HOUND: Card = Card("lava_hound", 7)
    LIGHTNING: Card = Card("lightning", 6)
    LUMBERJACK: Card = Card("lumberjack", 4)
    MAGIC_ARCHER: Card = Card("magic_archer", 4)
    MEGA_KNIGHT: Card = Card("mega_knight", 7)
    MEGA_MINION: Card = Card("mega_minion", 3)
    MIGHTY_MINER: Card = Card("mighty_miner", 4)
    MINER: Card = Card("miner", 3)
    MINIONS: Card = Card("minions", 3)
    MINION_HORDE: Card = Card("minion_horde", 5)
    MINIPEKKA: Card = Card("minipekka", 4)
    MIRROR: Card = Card("mirror", -1)
    MONK: Card = Card("monk", 5)
    MORTAR: Card = Card("mortar", 4)
    MOTHER_WITCH: Card = Card("mother_witch", 4)
    MUSKETEER: Card = Card("musketeer", 4)
    NIGHT_WITCH: Card = Card("night_witch", 4)
    PEKKA: Card = Card("pekka", 7)
    PHOENIX: Card = Card("phoenix", 4)
    POISON: Card = Card("poison", 4)
    PRINCE: Card = Card("prince", 5)
    PRINCESS: Card = Card("princess", 3)
    RAGE: Card = Card("rage", 2)
    RAM_RIDER: Card = Card("ram_rider", 5)
    RASCALS: Card = Card("rascals", 5)
    ROCKET: Card = Card("rocket", 6)
    ROYAL_DELIVERY: Card = Card("royal_delivery", 3)
    ROYAL_GHOST: Card = Card("royal_ghost", 3)
    ROYAL_GIANT: Card = Card("royal_giant", 6)
    ROYAL_HOGS: Card = Card("royal_hogs", 5)
    ROYAL_RECRUITS: Card = Card("royal_recruits", 7)
    SKELETONS: Card = Card("skeletons", 1)
    SKELETON_ARMY: Card = Card("skeleton_army", 3)
    SKELETON_BARREL: Card = Card("skeleton_barrel", 3)
    SKELETON_DRAGONS: Card = Card("skeleton_dragons", 4)
    SKELETON_KING: Card = Card("skeleton_king", 4)
    SPARKY: Card = Card("sparky", 6)
    SPEAR_GOBLINS: Card = Card("spear_goblins", 2)
    TESLA: Card = Card("tesla", 4)
    THE_LOG: Card = Card("the_log", 2)
    THREE_MUSKETEERS: Card = Card("three_musketeers", 9)
    TOMBSTONE: Card = Card("tombstone", 3)
    TORNADO: Card = Card("tornado", 3)
    VALKYRIE: Card = Card("valkyrie", 4)
    WALL_BREAKERS: Card = Card("wall_breakers", 2)
    WITCH: Card = Card("witch", 5)
    WIZARD: Card = Card("wizard", 5)
    X_BOW: Card = Card("x_bow", 6)
    ZAP: Card = Card("zap", 2)
    ZAPPIES: Card = Card("zappies", 4)

    def dict(self):
        return {k: v for k, v in asdict(self).items()}


Cards = _CardsNamespace()
